新規作成しました。
vrm-c/vrm-specification pull request #280
Opened 2021-06-23 10:56 UTC by ousttrue

#213

2021-06-23 11:10 UTC, Santarh requested changes
乗算で定義する方が "拡張らしい" ので良いと思います！
指摘の点は修正した方が良さそうです。

typo は全体で修正した方が良さそう
`s/Multiplyer/Multiplier/g` 
`s/multiplyer/multiplier/g`

2021-06-23 11:10 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/README.ja.md
> +# VRMC_materials_hdr_emissiveMultiplyer
`Multiplyer` となっていますが、英語として正しそうなのは `Multiplier` ですね

2021-06-23 11:10 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/README.ja.md
> +HDR 向けに EmissiveFactor を 1より大きい値に拡張することができます。
`HDR` もなかなか曖昧な感じがしてきたので、簡潔に以下のような文で良さそうです。

`1 よりも大きい値の EmissiveFactor を持つことができます。`

2021-06-23 11:10 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/README.ja.md
> +対象 material の material.emissiveFactor を emissiveMultiplyer で乗算した値で上書きします。
この値が linear であることを明示した方が良さそうです

2021-06-23 11:10 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/README.ja.md
> +以下のように変換してください。
`emissiveFactor` とは linear 空間で乗算されることを明示した方が良さそうです

2021-06-23 11:10 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/schema/VRMC_materials_hdr_emissiveMultiplyer.json
> +            "default": 1.0
👍

2021-06-23 11:10 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/README.ja.md
> +    let emissiveMultiplyer = max_component;
`max_component` を用いて Export する例が書かれていて良さそうです

2021-06-23 11:14 UTC, ousttrue commented on specification/VRMC_materials_hdr_emissiveMultiplyer-1.0_draft/README.ja.md
> +# VRMC_materials_hdr_emissiveMultiplyer
SpellChecker するの忘れてたー

2021-06-23 11:37 UTC, Santarh requested changes
ほぼほぼよさそう

2021-06-23 11:37 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplier-1.0_draft/README.ja.md
> +# VRMC_materials_hdr_emissiveMultiplier
👍

2021-06-23 11:37 UTC, Santarh commented on specification/VRMC_materials_hdr_emissiveMultiplier-1.0_draft/README.ja.md
> +| emissiveMultiplier | number | A multiplier for emissiveFactor in linear color space | ✅    |
なんというか厳密な話ですが、リニアの場合は `color space` ではなくて大丈夫です。
単なる `linear` で良いです。

ここの文は簡潔に `A multiplier for emissiveFactor.` でよさそうです。
リニアの定義に関しては下の説明文の 2 文目にあるとよさそうです。
`この値はリニアです。`
`This value is linear.`

2021-06-23 11:55 UTC, Santarh approved these changes
ワイはよさそう

2021-06-23 11:56 UTC, ousttrue commented
@FMS-Cat よろしくお願いします。

2021-06-24 03:42 UTC, FMS-Cat approved these changes
良さそうです。

2021-06-24 04:58 UTC, merged

2021-06-25 09:10 UTC, ousttrue commented
![bluaaa](https://user-images.githubusercontent.com/68057/123400286-8bd03200-d5e0-11eb-9108-81e5b6206d67.jpg)
例。