change (1.0, SpringBone): ban descendant of joint node to be a center node of spring bone joints
vrm-c/vrm-specification pull request #383
Opened 2022-06-30 10:46 UTC by 0b5vr

### Description

@Santarh さんの指摘に基づきます。

centerには対象となるjointの子孫を指定できない旨を仕様に追加しました。

### Points need review

- [ ] こんな感じの書き方で良いでしょうか？
- [ ] Joint自身について、いかがいたしましょう？
    - 私は許可する方向性が良いと思いますが、これについて仕様に明記したほうが良いでしょうか？

2022-06-30 10:59 UTC, Santarh requested changes
ありがとうございます。

１点、例外対象が狭すぎるように思います。

2022-06-30 10:59 UTC, Santarh commented on specification/VRMC_springBone-1.0-beta/README.md
> +The center node cannot be a descendant of the joint node.
ここでは `the` と指定があるのでおそらく `center` が含まれる joint node 自身のみを指しているのだろうと思います。
しかし指定できない joint node は、`center` 自身が対象とする joint node のみならず、その VRM モデル内のすべての joint node の子孫になるかなと思います。

そうでなければ、ほかの joint node の影響下に置かれることになるので、処理順の問題が発生してしまいます。

2022-07-01 05:11 UTC, 0b5vr commented on specification/VRMC_springBone-1.0-beta/README.md
> +The center node cannot be a descendant of the joint node.
なるほど、それは考慮漏れでした。

ちょっと待ってください、そもそもcenterって当該Jointの先祖およびJointそれ自身以外にはなり得なくないですか？
理論上は、髪の毛のcenterを腕に設定することはできると思いますが、相当変な挙動になると思います（手を動かすと髪の毛が揺れる）。

2022-07-01 06:35 UTC, Santarh commented on specification/VRMC_springBone-1.0-beta/README.md
> +The center node cannot be a descendant of the joint node.
そうですね！同意します。
> そもそもcenterって当該Jointの先祖およびJointそれ自身以外にはなり得なくないですか？

まとめ直すとこんな感じでしょうか。
- center に指定する node は、その Spring の 0 番目の Joint か、その祖先 node である必要がある
- center に指定する node は、他の Spring に属する SpringJoint およびその子孫であってはならない

2022-07-04 07:49 UTC, 0b5vr commented on specification/VRMC_springBone-1.0-beta/README.md
> +The center node cannot be a descendant of the joint node.
はい、良さそうです。その方向性で修正します。

2022-07-04 08:09 UTC, 0b5vr commented on specification/VRMC_springBone-1.0-beta/README.md
> +The center node cannot be a descendant of the joint node.
@Santarh 頂いた方向性で修正をしました。再レビューお願いします。

2022-07-06 04:47 UTC, Santarh approved these changes
よさそうです。ありがとうございます。

2022-07-06 04:47 UTC, Santarh commented on specification/VRMC_springBone-1.0-beta/README.ja.md
> +`center` は、SpringChain単位で指定します。
よさそうです。

2022-07-06 04:47 UTC, Santarh commented on specification/VRMC_springBone-1.0-beta/README.ja.md
> +また、Centerノードには、他のSpringChainのJointノードおよびその子孫を指定することはできません。
よさそうです。

2022-07-06 07:58 UTC, merged