change: set minimum and maximum for most of MToon number values
vrm-c/vrm-specification pull request #402
Opened 2022-09-21 11:11 UTC by 0b5vr

### Description

MToonの各数値について、mininumとmaximumを設定しました。

### Points need review

- [ ] matcapFactorのmaximumは必要ないと思いますが、相違ないですか？
- [ ] parametricRimColorFactorのmaximumは必要ないと思いますが、相違ないですか？
- [ ] outlineColorFactorのmaximumは必要だと思いますが、相違ないですか？

2022-09-21 11:29 UTC, Santarh approved these changes
良いと思います。追って UniVRM の matcapFactor の実装も変えます。

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +        "maximum": 1.0
値こそ Linear で記録されているが、sRGB Color 想定なのでこれでヨシ

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "maximum": 1.0
0-1 のファクターなのでヨシ

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "maximum": 1.0
0-1 のファクターなのでヨシ

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +        "minimum": 0.0
RimLighting の項は加算項で HDR を前提として良いので maximum はなくて良い

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +        "minimum": 0.0
RimLighting の項は加算項で HDR を前提として良い

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "maximum": 1.0
0-1 のファクター

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "minimum": 0.0
フレネルは非負であればよい。
厳密には 0.0 の場合は避けたいとは思うが、 JSONSchema 的にはどうしようもないと思うのでこれでよさそう。

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "minimum": 0.0
Outline Width は非負であればよい

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +        "maximum": 1.0
OutlineColor は値こそ Linear だが、sRGB Color 想定なのでこれでよい

2022-09-21 11:29 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "maximum": 1.0
0-1 のファクター

2022-09-21 11:54 UTC, Santarh requested changes
議論した結果 `matcapFactor` `parametricRimColorFactor` について制限したほうが良さそう

2022-09-21 11:54 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +        "minimum": 0.0
Rim Lighting の項はたしかに加算項だが、その Value が 1.0 を超える範囲である必然性はない。
以下の理由が挙げられる。
- glTF 本体では Factor が 1.0 を超えることを許容していない（拡張では許容される）
- 加算項だからこそ、加算項自体が 1.0 を超えなくても、全体として 1.0 を超えることができる

2022-09-21 12:01 UTC, 0b5vr commented
上記の議論に基づき、リム項にmaximum: 1.0を追加しました。

2022-09-21 12:05 UTC, Santarh approved these changes
LGTM

2022-09-22 02:17 UTC, 0b5vr commented on specification/VRMC_materials_mtoon-1.0-beta/schema/VRMC_materials_mtoon.schema.json
> +      "minimum": 0.0
一応、 `exclusiveMinimum` というプロパティがあったりはします……

`parametricRimFresnelPowerFactor` は、0にするとリムの形が一様な1.0になるという解釈でいます。

2022-09-22 03:02 UTC, merged