change (MToon): clarify transform order of uv scroll
vrm-c/vrm-specification pull request #415
Opened 2022-11-21 02:03 UTC by 0b5vr

will resolve #412

### Description

MToonのUVアニメーションについて、適用順によっては、平行移動と回転を同時に適用したときに時間経過に応じてアニメーション速度が加速していく挙動となります。
本PRでは、UVアニメーションの適用順を仕様内で明記し、この加速していく挙動でない方を標準とします。

また、全体の文章の流れを意識し、一部仕様文の並び替えを行いました。

### Points need review

- [ ] コードに誤りはないでしょうか？
    - 行列の定義については、 `KHR_texture_transform` のサンプルコードに基づいて、column originとしました。コード内にコメントでも表記してあります。
- [ ] 文言について、これで問題なく伝わりますでしょうか？
    - 「intrinsicに平行移動 → 回転の順」の箇所、過不足なく明快な表現でしょうか。

2022-11-28 07:33 UTC, Santarh requested changes
いくつか指摘点がありますが、おおむねよさそうです。

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +スクロールの向きは、設定値が正の場合に UV が正の方向に単調増加する方向です。
よさそう

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +> サンプルモデル「[VRMC_materials_mtoon UV Animation Test](../../samples/VRMC_materials_mtoon_UV_Animation_Test/)」も参照ください。
よさそう

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +さらに $c = \cos({\rm rotation}), s = \sin({\rm rotation})$ と置いたとき、
`c =` と `s = ` の置き換えはせず行列上に直接 `cos(rotation)` と書いてしまった方が分かりやすい気もします

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +```
行列計算として問題はなさそうです。

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +```
GitHub Markdown は TeX ライク記法をかけたんですね

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +マスクテクスチャがアサインされていない場合、各数値で設定した値がそのまま適用されます。
よさそう

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +// note that the matrix is defined in column-origin
これいつも混乱するんですけど、ここでいう `column-origin` とは
メモリレイアウト、もとい `mat2()` での指定順序が column major だという意味ですよね？
`mat2(a,b,c,d)` が数学的行列表記として以下になる、という意味。
```math
\begin{bmatrix} a & c \\ b & d  \end{bmatrix}
```

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +) * ( uv - 0.5 ) + 0.5;
回転部分の行列の乗算は `matrix * vector` になっているので自明にこうなっている、と。
```math
\begin{pmatrix} {\rm uv}'.x \\ {\rm uv}'.y \end{pmatrix} =
\begin{bmatrix} \rm{rotationCos} & \rm{rotationSin} \\ -\rm{rotationSin} & \rm{rotationCos} \end{bmatrix}
\begin{bmatrix} \rm{uv.x} - 0.5 \\ \rm{uv.y} -0.5 \end{bmatrix} +
\begin{bmatrix}  0.5 \\ 0.5 \end{bmatrix}
```

2022-11-28 07:33 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +// note that the matrix is defined in column-origin
実世界の行列計算ライブラリに通じていないと結構わかりづらいコメントかなと感じました。
`note that the order of the matrix constructor arguments is defined in column-major.` とかなのかなあ……

2022-11-30 08:39 UTC, 0b5vr commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +// note that the matrix is defined in column-origin
うわーーーー最近めちゃくちゃcolumn-majorと間違えてcolumn-originって言っちゃってた気がする。直します 🙇

2022-11-30 08:41 UTC, 0b5vr commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +さらに $c = \cos({\rm rotation}), s = \sin({\rm rotation})$ と置いたとき、
了解です！

2022-11-30 08:45 UTC, 0b5vr commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +さらに $c = \cos({\rm rotation}), s = \sin({\rm rotation})$ と置いたとき、
対応しました @ https://github.com/vrm-c/vrm-specification/pull/415/commits/938885dbb40b83c031841a584efb206b231236fe

2022-12-01 04:59 UTC, Santarh approved these changes
LGTM

2022-12-01 04:59 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +) * ( uv - 0.5 ) + 0.5;
う～ん、悩ましいところではありますが……
行列を読める人であればどちらでも構わないとは思うので、
全部変換行列になっていたほうが綺麗そうなので、今のままで良さそうです。

2022-12-01 04:59 UTC, Santarh commented on specification/VRMC_materials_mtoon-1.0/README.ja.md
> +// note that the matrix is defined in column-major
単純に `column-major` とだけ言うと「行ベクトル優先表現である」ということだけを指し示しているという気持ちにはなりますが
英語 wikipedia にもこういう記事があるし、伝わるとは思うのでこれで OK そう。
https://en.wikipedia.org/wiki/Row-_and_column-major_order

2022-12-01 09:54 UTC, merged